#############################################################################
# Makefile for building: libTabbedEditor.so
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  TabbedEditor.pro
# Template: lib
# Command: /home/rolf/Qt/5.15.2/gcc_64/bin/qmake -o Makefile TabbedEditor.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DWITH_TESTS -D'RELATIVE_PLUGIN_PATH="../lib/qtcreator/plugins"' -D'RELATIVE_LIBEXEC_PATH="../libexec/qtcreator"' -D'RELATIVE_DATA_PATH="../share/qtcreator"' -D'RELATIVE_DOC_PATH="../share/doc/qtcreator"' -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x050900 -DQT_USE_QSTRINGBUILDER -DTABBEDEDITOR_LIBRARY -DQT_QML_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/rolf/Projects/QT/plugin/TabbedEditor"'
CFLAGS        = -pipe -g -fvisibility=hidden -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-noexcept-type -g -std=gnu++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../qt-creator-master/src -I../../qt-creator-master/src -I../../qt-creator-master/src/libs -I/home/rolf/Projects/QT/qt-creator-master/tools -I../../qt-creator-master/src/plugins -I../../qt-creator-master/src/libs -I../../qt-creator-master/src/libs/3rdparty -I../../qt-creator-master/src/libs/3rdparty/syntax-highlighting/src/lib -I../../qt-creator-master/src/libs/3rdparty/syntax-highlighting/autogenerated/src/lib -I. -I../../../../Qt/5.15.2/gcc_64/include -I../../../../Qt/5.15.2/gcc_64/include/QtWidgets -I../../../../Qt/5.15.2/gcc_64/include/QtGui -I../../../../Qt/5.15.2/gcc_64/include/QtTest -I../../../../Qt/5.15.2/gcc_64/include/QtConcurrent -I../../../../Qt/5.15.2/gcc_64/include/QtNetwork -I../../../../Qt/5.15.2/gcc_64/include/QtCore -I.moc/debug-shared -I/usr/include/libdrm -I../../../../Qt/5.15.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/rolf/Qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/rolf/Qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/rolf/Qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TabbedEditor4.82.0
DISTDIR = /home/rolf/Projects/QT/plugin/TabbedEditor/.obj/debug-shared/TabbedEditor4.82.0
LINK          = g++
LFLAGS        = -Wl,-z,origin '-Wl,-rpath,$$ORIGIN:$$ORIGIN/../:$$ORIGIN/.' -Wl,--no-undefined -Wl,-rpath,/home/rolf/Qt/5.15.2/gcc_64/lib -shared -Wl,-soname,libTabbedEditor.so
LIBS          = $(SUBLIBS) -L/home/rolf/Projects/QT/qt-creator-master/lib/qtcreator -L/home/rolf/Projects/QT/qt-creator-master/lib/qtcreator/plugins -lCore -lProjectExplorer -lTextEditor -lQtcSsh -lAggregation -lExtensionSystem -lUtils -lKSyntaxHighlighting /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Widgets.so /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Gui.so /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Test.so /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Concurrent.so /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Network.so /home/rolf/Qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/debug-shared/

####### Files

SOURCES       = tabbar.cpp \
		tabbededitor.cpp .rcc/qrc_res.cpp \
		.moc/debug-shared/moc_tabbar.cpp \
		.moc/debug-shared/moc_tabbededitor.cpp
OBJECTS       = .obj/debug-shared/tabbar.o \
		.obj/debug-shared/tabbededitor.o \
		.obj/debug-shared/qrc_res.o \
		.obj/debug-shared/moc_tabbar.o \
		.obj/debug-shared/moc_tabbededitor.o
DIST          = CMakeLists.txt \
		TabbedEditor.json.in \
		CMakeLists.txt \
		CMakeLists.txt.user \
		LICENSE \
		README.md \
		TabbedEditor.json.in \
		resources/icons/close_button_dark.png \
		resources/icons/close_button_light_grey.png \
		resources/styles/default.qss \
		tab.png \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../qt-creator-master/qtcreator_ide_branding.pri \
		../../qt-creator-master/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../qt-creator-master/src/plugins/projectexplorer/projectexplorer_dependencies.pri \
		../../qt-creator-master/src/shared/syntax/syntax_shared.pri \
		../../qt-creator-master/src/plugins/texteditor/texteditor_dependencies.pri \
		../../qt-creator-master/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../qt-creator-master/src/libs/utils/utils_dependencies.pri \
		../../qt-creator-master/src/libs/aggregation/aggregation_dependencies.pri \
		../../qt-creator-master/src/libs/ssh/ssh_dependencies.pri \
		../../qt-creator-master/src/libs/3rdparty/syntax-highlighting/syntax-highlighting_dependencies.pri \
		../../qt-creator-master/qtcreator.pri \
		../../qt-creator-master/src/rpath.pri \
		../../qt-creator-master/src/qtcreatorplugin.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/hide_symbols.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/testlib_defines.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/uic.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		TabbedEditor.pro include/plog/Appenders/AndroidAppender.h \
		include/plog/Appenders/ColorConsoleAppender.h \
		include/plog/Appenders/ConsoleAppender.h \
		include/plog/Appenders/DebugOutputAppender.h \
		include/plog/Appenders/EventLogAppender.h \
		include/plog/Appenders/IAppender.h \
		include/plog/Appenders/RollingFileAppender.h \
		include/plog/Converters/NativeEOLConverter.h \
		include/plog/Converters/UTF8Converter.h \
		include/plog/Formatters/CsvFormatter.h \
		include/plog/Formatters/FuncMessageFormatter.h \
		include/plog/Formatters/MessageOnlyFormatter.h \
		include/plog/Formatters/TxtFormatter.h \
		include/plog/Init.h \
		include/plog/Log.h \
		include/plog/Logger.h \
		include/plog/Record.h \
		include/plog/Severity.h \
		include/plog/Util.h \
		include/plog/WinApi.h \
		tabbar.h \
		tabbededitor.h \
		tabbededitor_global.h \
		tabbededitorconstants.h tabbar.cpp \
		tabbededitor.cpp
QMAKE_TARGET  = TabbedEditor
DESTDIR       = ../../qt-creator-master/lib/qtcreator/plugins/
TARGET        = libTabbedEditor.so
TARGETD       = libTabbedEditor.so


first: all
####### Build rules

../../qt-creator-master/lib/qtcreator/plugins/libTabbedEditor.so:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../qt-creator-master/lib/qtcreator/plugins/ || mkdir -p ../../qt-creator-master/lib/qtcreator/plugins/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../qt-creator-master/lib/qtcreator/plugins/$(TARGET)



Makefile: TabbedEditor.pro ../../../../Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../qt-creator-master/qtcreator_ide_branding.pri \
		../../qt-creator-master/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../qt-creator-master/src/plugins/projectexplorer/projectexplorer_dependencies.pri \
		../../qt-creator-master/src/shared/syntax/syntax_shared.pri \
		../../qt-creator-master/src/plugins/texteditor/texteditor_dependencies.pri \
		../../qt-creator-master/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../qt-creator-master/src/libs/utils/utils_dependencies.pri \
		../../qt-creator-master/src/libs/aggregation/aggregation_dependencies.pri \
		../../qt-creator-master/src/libs/ssh/ssh_dependencies.pri \
		../../qt-creator-master/src/libs/3rdparty/syntax-highlighting/syntax-highlighting_dependencies.pri \
		../../qt-creator-master/qtcreator.pri \
		../../qt-creator-master/src/rpath.pri \
		../../qt-creator-master/src/qtcreatorplugin.pri \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/hide_symbols.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/testlib_defines.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/uic.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		TabbedEditor.pro \
		TabbedEditor.json.in \
		resources/res.qrc
	$(QMAKE) -o Makefile TabbedEditor.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/unix.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/linux.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/qconfig.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf:
../../qt-creator-master/qtcreator_ide_branding.pri:
../../qt-creator-master/src/plugins/coreplugin/coreplugin_dependencies.pri:
../../qt-creator-master/src/plugins/projectexplorer/projectexplorer_dependencies.pri:
../../qt-creator-master/src/shared/syntax/syntax_shared.pri:
../../qt-creator-master/src/plugins/texteditor/texteditor_dependencies.pri:
../../qt-creator-master/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../../qt-creator-master/src/libs/utils/utils_dependencies.pri:
../../qt-creator-master/src/libs/aggregation/aggregation_dependencies.pri:
../../qt-creator-master/src/libs/ssh/ssh_dependencies.pri:
../../qt-creator-master/src/libs/3rdparty/syntax-highlighting/syntax-highlighting_dependencies.pri:
../../qt-creator-master/qtcreator.pri:
../../qt-creator-master/src/rpath.pri:
../../qt-creator-master/src/qtcreatorplugin.pri:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/hide_symbols.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/qt.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/resources.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/moc.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/testlib_defines.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/uic.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf:
../../../../Qt/5.15.2/gcc_64/mkspecs/features/lex.prf:
TabbedEditor.pro:
TabbedEditor.json.in:
resources/res.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile TabbedEditor.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ../../qt-creator-master/lib/qtcreator/plugins/libTabbedEditor.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/plog/Appenders/AndroidAppender.h include/plog/Appenders/ColorConsoleAppender.h include/plog/Appenders/ConsoleAppender.h include/plog/Appenders/DebugOutputAppender.h include/plog/Appenders/EventLogAppender.h include/plog/Appenders/IAppender.h include/plog/Appenders/RollingFileAppender.h include/plog/Converters/NativeEOLConverter.h include/plog/Converters/UTF8Converter.h include/plog/Formatters/CsvFormatter.h include/plog/Formatters/FuncMessageFormatter.h include/plog/Formatters/MessageOnlyFormatter.h include/plog/Formatters/TxtFormatter.h include/plog/Init.h include/plog/Log.h include/plog/Logger.h include/plog/Record.h include/plog/Severity.h include/plog/Util.h include/plog/WinApi.h tabbar.h tabbededitor.h tabbededitor_global.h tabbededitorconstants.h $(DISTDIR)/
	$(COPY_FILE) --parents tabbar.cpp tabbededitor.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../qt-creator-master/lib/qtcreator/plugins/$(TARGET) 
	-$(DEL_FILE) .qmake.stash /home/rolf/Projects/QT/plugin/TabbedEditor/TabbedEditor.json
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: .rcc/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_res.cpp
.rcc/qrc_res.cpp: resources/res.qrc \
		../../../../Qt/5.15.2/gcc_64/bin/rcc \
		resources/styles/default.qss \
		resources/icons/close_button_light_grey.png \
		resources/icons/close_button_dark.png
	/home/rolf/Qt/5.15.2/gcc_64/bin/rcc -name res resources/res.qrc -o .rcc/qrc_res.cpp

compiler_moc_predefs_make_all: .moc/debug-shared/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .moc/debug-shared/moc_predefs.h
.moc/debug-shared/moc_predefs.h: ../../../../Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-noexcept-type -g -std=gnu++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -dM -E -o .moc/debug-shared/moc_predefs.h ../../../../Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: .moc/debug-shared/moc_tabbar.cpp .moc/debug-shared/moc_tabbededitor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/debug-shared/moc_tabbar.cpp .moc/debug-shared/moc_tabbededitor.cpp
.moc/debug-shared/moc_tabbar.cpp: tabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QTabBar \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		.moc/debug-shared/moc_predefs.h \
		../../../../Qt/5.15.2/gcc_64/bin/moc
	/home/rolf/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /home/rolf/Projects/QT/plugin/TabbedEditor/.moc/debug-shared/moc_predefs.h -I/home/rolf/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/home/rolf/Projects/QT/plugin/TabbedEditor -I/home/rolf/Projects/QT/qt-creator-master/src -I/home/rolf/Projects/QT/qt-creator-master/src -I/home/rolf/Projects/QT/qt-creator-master/src/libs -I/home/rolf/Projects/QT/qt-creator-master/tools -I/home/rolf/Projects/QT/qt-creator-master/src/plugins -I/home/rolf/Projects/QT/qt-creator-master/src/libs -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty/syntax-highlighting/src/lib -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty/syntax-highlighting/autogenerated/src/lib -I/home/rolf/Projects/QT/plugin/TabbedEditor -I/home/rolf/Qt/5.15.2/gcc_64/include -I/home/rolf/Qt/5.15.2/gcc_64/include/QtWidgets -I/home/rolf/Qt/5.15.2/gcc_64/include/QtGui -I/home/rolf/Qt/5.15.2/gcc_64/include/QtTest -I/home/rolf/Qt/5.15.2/gcc_64/include/QtConcurrent -I/home/rolf/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/rolf/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tabbar.h -o .moc/debug-shared/moc_tabbar.cpp

.moc/debug-shared/moc_tabbededitor.cpp: tabbededitor.h \
		tabbededitor_global.h \
		../../qt-creator-master/src/libs/extensionsystem/iplugin.h \
		../../qt-creator-master/src/libs/extensionsystem/extensionsystem_global.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QLoggingCategory \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qloggingcategory.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QObject \
		.moc/debug-shared/moc_predefs.h \
		../../../../Qt/5.15.2/gcc_64/bin/moc
	/home/rolf/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /home/rolf/Projects/QT/plugin/TabbedEditor/.moc/debug-shared/moc_predefs.h -I/home/rolf/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/home/rolf/Projects/QT/plugin/TabbedEditor -I/home/rolf/Projects/QT/qt-creator-master/src -I/home/rolf/Projects/QT/qt-creator-master/src -I/home/rolf/Projects/QT/qt-creator-master/src/libs -I/home/rolf/Projects/QT/qt-creator-master/tools -I/home/rolf/Projects/QT/qt-creator-master/src/plugins -I/home/rolf/Projects/QT/qt-creator-master/src/libs -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty/syntax-highlighting/src/lib -I/home/rolf/Projects/QT/qt-creator-master/src/libs/3rdparty/syntax-highlighting/autogenerated/src/lib -I/home/rolf/Projects/QT/plugin/TabbedEditor -I/home/rolf/Qt/5.15.2/gcc_64/include -I/home/rolf/Qt/5.15.2/gcc_64/include/QtWidgets -I/home/rolf/Qt/5.15.2/gcc_64/include/QtGui -I/home/rolf/Qt/5.15.2/gcc_64/include/QtTest -I/home/rolf/Qt/5.15.2/gcc_64/include/QtConcurrent -I/home/rolf/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/rolf/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tabbededitor.h -o .moc/debug-shared/moc_tabbededitor.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

.obj/debug-shared/tabbar.o: tabbar.cpp tabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QTabBar \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		tabbededitorconstants.h \
		../../qt-creator-master/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../../qt-creator-master/src/plugins/coreplugin/core_global.h \
		../../qt-creator-master/src/plugins/coreplugin/coreconstants.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QtGlobal \
		../../qt-creator-master/src/plugins/coreplugin/icontext.h \
		../../qt-creator-master/src/plugins/coreplugin/helpitem.h \
		../../qt-creator-master/src/libs/utils/optional.h \
		../../qt-creator-master/src/libs/3rdparty/optional/optional.hpp \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QString \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QUrl \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QVariant \
		../../qt-creator-master/src/libs/utils/id.h \
		../../qt-creator-master/src/libs/utils/utils_global.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QList \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QMetaType \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QObject \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QPointer \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QWidget \
		../../qt-creator-master/src/plugins/coreplugin/actionmanager/command.h \
		../../qt-creator-master/src/libs/utils/hostosinfo.h \
		../../qt-creator-master/src/libs/utils/osspecificaspects.h \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/editormanager.h \
		../../qt-creator-master/src/plugins/coreplugin/idocument.h \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/documentmodel.h \
		../../qt-creator-master/src/libs/utils/fileutils.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QCoreApplication \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QDir \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdir.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfileinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QFileInfo \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QStringList \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QXmlStreamWriter \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qxmlstream.h \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/ieditor.h \
		../../qt-creator-master/src/libs/utils/textfileformat.h \
		../../qt-creator-master/src/plugins/coreplugin/fileiconprovider.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QStyle \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qstyle.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QFileIconProvider \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qfileiconprovider.h \
		../../qt-creator-master/src/plugins/projectexplorer/session.h \
		../../qt-creator-master/src/plugins/projectexplorer/projectexplorer_export.h \
		../../qt-creator-master/src/libs/utils/persistentsettings.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QDateTime \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdatetime.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QMenu \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qmenu.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qaction.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QTimer \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtimer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbasictimer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/QMouseEvent \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QShortcut \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qshortcut.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QFile \
		include/plog/Log.h \
		include/plog/Logger.h \
		include/plog/Appenders/IAppender.h \
		include/plog/Record.h \
		include/plog/Severity.h \
		include/plog/Util.h \
		include/plog/Init.h \
		include/plog/Formatters/CsvFormatter.h \
		include/plog/Formatters/TxtFormatter.h \
		include/plog/Appenders/RollingFileAppender.h \
		include/plog/Converters/UTF8Converter.h \
		include/plog/Converters/NativeEOLConverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/tabbar.o tabbar.cpp

.obj/debug-shared/tabbededitor.o: tabbededitor.cpp tabbededitor.h \
		tabbededitor_global.h \
		../../qt-creator-master/src/libs/extensionsystem/iplugin.h \
		../../qt-creator-master/src/libs/extensionsystem/extensionsystem_global.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QLoggingCategory \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qloggingcategory.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QObject \
		tabbededitorconstants.h \
		tabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QTabBar \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtabbar.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-creator-master/src/plugins/coreplugin/icore.h \
		../../qt-creator-master/src/plugins/coreplugin/core_global.h \
		../../qt-creator-master/src/plugins/coreplugin/icontext.h \
		../../qt-creator-master/src/plugins/coreplugin/helpitem.h \
		../../qt-creator-master/src/libs/utils/optional.h \
		../../qt-creator-master/src/libs/3rdparty/optional/optional.hpp \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QString \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QUrl \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QVariant \
		../../qt-creator-master/src/libs/utils/id.h \
		../../qt-creator-master/src/libs/utils/utils_global.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QList \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QMetaType \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QPointer \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qpointer.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QWidget \
		../../qt-creator-master/src/libs/utils/fileutils.h \
		../../qt-creator-master/src/libs/utils/hostosinfo.h \
		../../qt-creator-master/src/libs/utils/osspecificaspects.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QCoreApplication \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QDir \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qdir.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qfileinfo.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QFileInfo \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QStringList \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QXmlStreamWriter \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qxmlstream.h \
		../../qt-creator-master/src/libs/utils/qtcsettings.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QSettings \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/qsettings.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QRect \
		../../qt-creator-master/src/plugins/coreplugin/coreconstants.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QtGlobal \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/editormanager.h \
		../../qt-creator-master/src/plugins/coreplugin/idocument.h \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/documentmodel.h \
		../../qt-creator-master/src/plugins/coreplugin/editormanager/ieditor.h \
		../../qt-creator-master/src/libs/utils/textfileformat.h \
		../../qt-creator-master/src/libs/utils/stylehelper.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QStyle \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qstyle.h \
		../../qt-creator-master/src/libs/utils/theme/theme.h \
		../../../../Qt/5.15.2/gcc_64/include/QtGui/QBrush \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QAction \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qaction.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QMessageBox \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qdialog.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QMenu \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qmenu.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/QBoxLayout \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qlayout.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../../Qt/5.15.2/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../../Qt/5.15.2/gcc_64/include/QtCore/QFile \
		include/plog/Log.h \
		include/plog/Logger.h \
		include/plog/Appenders/IAppender.h \
		include/plog/Record.h \
		include/plog/Severity.h \
		include/plog/Util.h \
		include/plog/Init.h \
		include/plog/Formatters/CsvFormatter.h \
		include/plog/Formatters/TxtFormatter.h \
		include/plog/Appenders/RollingFileAppender.h \
		include/plog/Converters/UTF8Converter.h \
		include/plog/Converters/NativeEOLConverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/tabbededitor.o tabbededitor.cpp

.obj/debug-shared/qrc_res.o: .rcc/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/qrc_res.o .rcc/qrc_res.cpp

.obj/debug-shared/moc_tabbar.o: .moc/debug-shared/moc_tabbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_tabbar.o .moc/debug-shared/moc_tabbar.cpp

.obj/debug-shared/moc_tabbededitor.o: .moc/debug-shared/moc_tabbededitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_tabbededitor.o .moc/debug-shared/moc_tabbededitor.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/lib/qtcreator/plugins || mkdir -p $(INSTALL_ROOT)/lib/qtcreator/plugins
	$(QINSTALL_PROGRAM) ../../qt-creator-master/lib/qtcreator/plugins/$(TARGET) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

