#ifndef TABBEDEDITOR_GLOBAL_H
#define TABBEDEDITOR_GLOBAL_H

#if defined(TABBEDEDITOR_LIBRARY)
#  define TABBEDEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define TABBEDEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // TABBEDEDITOR_GLOBAL_H
